name: wake-api-test

on:
  push:
    path-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: sifive/wit/actions/init@v0.13.2
    - uses: sifive/environment-blockci-sifive/actions/wake@0.7.1

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Init Workspace
        uses: sifive/wit/actions/init@v0.13.2
        with:
          additional_packages: git@github.com:sifive/environment-blockci-sifive.git::0.7.1

      - name: Run test script
        uses: sifive/environment-blockci-sifive/actions/shell@0.7.1
        with:
          command: freedom-devicetree-tools/tests/test-wake-install.sh
